# Generated by Django 5.0.3 on 2024-03-20 21:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="workplace",
            name="country",
            field=models.CharField(default="", max_length=32),
        ),
        migrations.AddField(
            model_name="workplace",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
    ]
