# Generated by Django 5.0.3 on 2024-03-21 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_city_coworking_farm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coworking',
            name='image_url',
            field=models.URLField(blank=True, default=None),
        ),
    ]
