# Generated by Django 5.0.3 on 2024-03-21 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_coworking_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='image_url',
            field=models.URLField(blank=True, default=None),
        ),
    ]
