# Generated by Django 5.0.3 on 2024-03-20 16:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core_user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True, db_index=True, max_length=254, null=True, unique=True
            ),
        ),
    ]
